language: generic
services:
  - docker

env:
  matrix:
    - ROS_DISTRO="foxy"

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .tello_ros_ci -b master
script:
  - .tello_ros_ci/travis.sh
